<Project>
  <PropertyGroup>
    <Version>1.0.9</Version>
    <AssemblyVersion>1.0.9.0</AssemblyVersion>
    <FileVersion>1.0.9.0</FileVersion>
    <InformationalVersion>1.0.9</InformationalVersion>
    <Company>Srlily</Company>
    <Product>Srlily Updater Test</Product>
    <Authors>Srlily</Authors>
    <Copyright>Copyright (c) 2026 Srlily</Copyright>
    <RepositoryUrl>https://github.com/Srlily/Srlily-Updater-Tset</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <NeutralLanguage>zh-CN</NeutralLanguage>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>
