<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <AssemblyName>Srlily.UpdaterTset</AssemblyName>
    <RootNamespace>Srlily.UpdaterTset</RootNamespace>
    <StartupObject>Srlily.UpdaterTset.Program</StartupObject>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Config\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Locales\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Data\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Plugins\**\*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\**\*" CopyToOutputDirectory="PreserveNewest" Exclude="Assets\app.ico" />
    <Content Include="updater.config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\latest.json" Link="latest.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\README.md" Link="README.md" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\CHANGELOG.md" Link="CHANGELOG.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
